/**
 * Códigos de error genéricos compartidos entre microservicios.
 */
export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  BAD_GATEWAY = 'BAD_GATEWAY',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT',
  INVALID_REQUEST_PATH = 'INVALID_REQUEST_PATH',
  MALFORMED_URL = 'MALFORMED_URL',
  DEVICE_FINGERPRINT_REQUIRED = 'DEVICE_FINGERPRINT_REQUIRED',

  // 🔹 Dominio seguridad
  DEVICE_NOT_TRUSTED = 'DEVICE_NOT_TRUSTED',
  USER_BLOCKED = 'USER_BLOCKED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  COUNTRY_NOT_TRUSTED = "COUNTRY_NOT_TRUSTED",
  SECURITY_CHALLENGE_REQUIRED= 'SECURITY_CHALLENGE_REQUIRED',
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD',
  SAME_PASSWORD_NOT_ALLOWED = 'SAME_PASSWORD_NOT_ALLOWED',

  // 🔹 2FA
  TWO_FACTOR_ALREADY_ENABLED = 'TWO_FACTOR_ALREADY_ENABLED',
  TWO_FACTOR_NOT_ENABLED = 'TWO_FACTOR_NOT_ENABLED',
  INVALID_TOTP_CODE = 'INVALID_TOTP_CODE',
  TWO_FACTOR_SETUP_NOT_INITIATED = 'TWO_FACTOR_SETUP_NOT_INITIATED',

  // 🔹 Trusted countries
  TRUSTED_COUNTRY_ALREADY_EXISTS = 'TRUSTED_COUNTRY_ALREADY_EXISTS',
  TRUSTED_COUNTRY_NOT_FOUND = 'TRUSTED_COUNTRY_NOT_FOUND',
  TRUSTED_COUNTRY_LIMIT_REACHED = 'TRUSTED_COUNTRY_LIMIT_REACHED',

  // 🔹 Sessions
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',

  // 🔹 Email verification
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',
}