/**
 * Códigos de error genéricos compartidos entre microservicios.
 */
export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  BAD_GATEWAY = 'BAD_GATEWAY',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT',
  INVALID_REQUEST_PATH = 'INVALID_REQUEST_PATH',
  MALFORMED_URL = 'MALFORMED_URL',
  DEVICE_FINGERPRINT_REQUIRED = 'DEVICE_FINGERPRINT_REQUIRED',

  // 🔹 Dominio seguridad
  DEVICE_NOT_TRUSTED = 'DEVICE_NOT_TRUSTED',
  USER_BLOCKED = 'USER_BLOCKED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  COUNTRY_NOT_TRUSTED = "COUNTRY_NOT_TRUSTED",
  SECURITY_CHALLENGE_REQUIRED= 'SECURITY_CHALLENGE_REQUIRED',
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
}