name: Setup Node Environment
description: Setup Node, pnpm, cache and prisma

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.3.0
      with:
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@v6.3.0
      with:
        node-version: 24
        check-latest: true
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Cache Prisma
      id: cache-prisma
      uses: actions/cache@v5.0.3
      with:
        path: |
          node_modules/.prisma
          services/**/generated/prisma
        key: prisma-${{ runner.os }}-${{ hashFiles('**/schema.prisma') }}-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Generate Prisma Client
      if: steps.cache-prisma.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm --filter auth-service exec prisma generate
