sonar.projectKey=saas-platform-backend
sonar.organization=aalejandrozuleta
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

sonar.sources=services,shared
sonar.tests=services,shared
sonar.typescript.tsconfigPaths=services/api-gateway/tsconfig.json,services/auth-service/tsconfig.json,shared/tsconfig.json

sonar.exclusions=\
**/dist/**,\
**/node_modules/**,\
**/coverage/**,\
**/*.d.ts,\
**/generated/**,\
docker/**,\
docs/**,\
**/*.module.ts,\
**/main.ts

sonar.test.inclusions=\
**/*.spec.ts,\
**/*.test.ts,\
**/__tests__/**

sonar.javascript.lcov.reportPaths=\
services/**/coverage/lcov.info,\
shared/**/coverage/lcov.info

sonar.coverage.exclusions=\
**/*.spec.ts,\
**/*.test.ts,\
**/__tests__/**,\
**/*.module.ts,\
**/main.ts,\
**/*.d.ts,\
**/generated/**

sonar.cpd.exclusions=\
**/*.spec.ts,\
**/*.test.ts,\
**/__tests__/**,\
**/generated/**

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=docker:S6504
sonar.issue.ignore.multicriteria.e1.resourceKey=**/Dockerfile*
