export const APP_CONFIG_REPOSITORY = Symbol('APP_CONFIG_REPOSITORY');
export const FEATURE_FLAG_REPOSITORY = Symbol('FEATURE_FLAG_REPOSITORY');
export const TENANT_CONFIG_REPOSITORY = Symbol('TENANT_CONFIG_REPOSITORY');
export const IP_RULE_REPOSITORY = Symbol('IP_RULE_REPOSITORY');
export const MAINTENANCE_WINDOW_REPOSITORY = Symbol('MAINTENANCE_WINDOW_REPOSITORY');
export const RATE_LIMIT_REPOSITORY = Symbol('RATE_LIMIT_REPOSITORY');
export const PASSWORD_POLICY_REPOSITORY = Symbol('PASSWORD_POLICY_REPOSITORY');
export const ALLOWED_DOMAIN_REPOSITORY = Symbol('ALLOWED_DOMAIN_REPOSITORY');
