FROM node:24-alpine

WORKDIR /app

ENV PNPM_STORE_PATH=/pnpm-store
RUN corepack enable

# Copiar workspace completo (necesario para pnpm workspaces)
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY .npmrc ./
COPY tsconfig.base.json ./

# Copiar solo lo necesario
COPY services ./services
COPY shared ./shared

# NOSONAR: pnpm install scripts required for prisma
RUN pnpm install --frozen-lockfile

WORKDIR /app/services/api-gateway

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
