FROM node:24-alpine

WORKDIR /app

ENV PNPM_STORE_PATH=/pnpm-store

# Instalar pnpm
RUN npm install -g pnpm

# Copiar archivos del workspace
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY tsconfig.base.json ./

# Copiar código
COPY services ./services
COPY shared ./shared

# Instalar dependencias
RUN pnpm install

WORKDIR /app/services/api-gateway

EXPOSE 3000

CMD ["pnpm", "run", "dev"]