/**
 * Eventos de seguridad anómalos.
 */
export enum AnomalyAuditEvent {
  NEW_COUNTRY_DETECTED = 'NEW_COUNTRY_DETECTED',
  IMPOSSIBLE_TRAVEL_DETECTED = 'IMPOSSIBLE_TRAVEL_DETECTED',
  SUSPICIOUS_IP_DETECTED = 'SUSPICIOUS_IP_DETECTED',
  TOO_MANY_FAILED_ATTEMPTS = 'TOO_MANY_FAILED_ATTEMPTS',
}
