/**
 * Eventos relacionados con autenticación.
 */
export enum AuthAuditEvent {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGIN_BLOCKED = 'LOGIN_BLOCKED',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  REGISTER_FAILED = 'REGISTER_FAILED',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  LOGIN_ATTEMPT = 'LOGIN_ATTEMPT',
  LOGIN_FAILED_EMAIL_NOT_FOUND = 'LOGIN_FAILED_EMAIL_NOT_FOUND',
  LOGIN_FAILED_PASSWORD = 'LOGIN_FAILED_PASSWORD',
  LOGIN_DEVICE_NOT_TRUSTED = 'LOGIN_DEVICE_NOT_TRUSTED',
  LOGIN_COUNTRY_NOT_TRUSTED = 'LOGIN_COUNTRY_NOT_TRUSTED',
}
