/**
 * Eventos relacionados con dispositivos.
 */
export enum DeviceAuditEvent {
  DEVICE_REGISTERED = 'DEVICE_REGISTERED',
  DEVICE_REMOVED = 'DEVICE_REMOVED',
  DEVICE_TRUSTED = 'DEVICE_TRUSTED',
  DEVICE_UNTRUSTED = 'DEVICE_UNTRUSTED',
  DEVICE_LIMIT_REACHED = 'DEVICE_LIMIT_REACHED',
}
