/**
 * Eventos relacionados con tokens.
 */
export enum TokenAuditEvent {
  REFRESH_TOKEN_ISSUED = 'REFRESH_TOKEN_ISSUED',
  REFRESH_TOKEN_REVOKED = 'REFRESH_TOKEN_REVOKED',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  ACCESS_TOKEN_REUSED = 'ACCESS_TOKEN_REUSED',
}
