/**
 * Eventos relacionados con autenticación de dos factores.
 */
export enum TwoFactorAuditEvent {
  TWO_FACTOR_ENABLED = 'TWO_FACTOR_ENABLED',
  TWO_FACTOR_DISABLED = 'TWO_FACTOR_DISABLED',
  TWO_FACTOR_CHALLENGE_SENT = 'TWO_FACTOR_CHALLENGE_SENT',
  TWO_FACTOR_SUCCESS = 'TWO_FACTOR_SUCCESS',
  TWO_FACTOR_FAILED = 'TWO_FACTOR_FAILED',
}
