server {
  listen 80;
  server_name localhost;
  resolver 127.0.0.11 ipv6=off valid=30s;

  # =====================
  # API GATEWAY
  # Cliente:  /api/v1/...
  # Gateway:  /v1/...
  # =====================
  location /api/ {
    set $api_gateway_upstream http://api-gateway:3000;

    # 🔴 ESTE rewrite ES OBLIGATORIO
    rewrite ^/api/?(.*)$ /$1 break;

    proxy_pass $api_gateway_upstream;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header X-Correlation-Id $request_id;
  }

  # =====================
  # ADMIN UIs (local)
  # =====================
  location /admin/grafana/ {
    set $grafana_upstream http://grafana:3000;
    proxy_pass $grafana_upstream;
  }

  location /admin/pgadmin/ {
    set $pgadmin_upstream http://pgadmin:80;
    proxy_pass $pgadmin_upstream;
  }

  location /admin/redis/ {
    set $redisinsight_upstream http://redisinsight:5540;
    proxy_read_timeout 60s;
    proxy_send_timeout 60s;
    proxy_pass $redisinsight_upstream;
  }

  location /admin/mongo/ {
    set $mongo_express_upstream http://mongo-express:8081;
    proxy_pass $mongo_express_upstream;
  }
}
