name: Detect Changed Services

on:
  workflow_call:
    outputs:
      services:
        description: Changed services
        value: ${{ jobs.detect.outputs.services }}

jobs:
  detect:
    runs-on: ubuntu-latest

    outputs:
      services: ${{ steps.changed.outputs.services }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect changes
        id: changed
        run: |
          SERVICES=$(git diff --name-only origin/main...HEAD \
            | grep '^services/' \
            | cut -d/ -f2 \
            | sort -u \
            | jq -R -s -c 'split("\n")[:-1]')
          echo "services=$SERVICES" >> $GITHUB_OUTPUT