name: Docs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Generate docs
        run: pnpm docs:code

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Debug docs output
        run: |
          echo "DOCS CONTENT:"
          ls -R docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4