name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/setup-node.yml

  sonar:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test coverage
        run: pnpm test:cov

      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}